# Generated by Django 3.2 on 2021-04-19 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zbozi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte text o maximální délce 100 znaků', max_length=100, verbose_name='Název zboží')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis zboží')),
                ('cena', models.FloatField(help_text='Zadejte nezáporné desetinné číslo', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cena')),
                ('stav', models.CharField(blank=True, choices=[('5', 'jako nový'), ('4', 'málo používaný'), ('3', 'často používaný'), ('2', 'opotřebovaný'), ('1', 'funkční vady')], default='3', help_text='Vyberte označení stavu', max_length=20, verbose_name='Stav zboží')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='zbozi/%Y/%m/%d/', verbose_name='Fotka zboží')),
                ('druh', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bazar.druh')),
            ],
            options={
                'ordering': ['-cena', 'nazev'],
            },
        ),
    ]
