# Generated by Django 3.2 on 2021-04-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_zbozi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druh',
            options={'ordering': ['oznaceni_druhu'], 'verbose_name': 'Druh zboží'},
        ),
        migrations.AlterModelOptions(
            name='zbozi',
            options={'ordering': ['-cena', 'nazev'], 'verbose_name': 'Zboží'},
        ),
    ]
