# Generated by Django 3.2 on 2021-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_auto_20210419_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zbozi',
            name='stav',
            field=models.IntegerField(blank=True, choices=[(5, 'jako nový'), (4, 'málo používaný'), (3, 'často používaný'), (2, 'opotřebovaný'), (1, 'funkční vady')], default=3, help_text='Vyberte označení stavu', max_length=1, verbose_name='Stav zboží'),
        ),
    ]
